name: Build Detect It Easy (Qt6)

env:
  TAG: "3.21"
  
on:
  workflow_dispatch:
  release:
    types: [created]
  
jobs:

  ubuntu-arm:
    name: Ubuntu arm64
    runs-on: ubuntu-26.04-arm

    # Run the entire build inside Ubuntu 25.10 ARM64.
    container:
      image: ubuntu:25.10

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Set timezone
        run: |
          export TZ=UTC
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
          echo $TZ > /etc/timezone
  
      - name: Install bootstrap dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install -y \
            git \
            ca-certificates
      
      - name: Clone DIE repository
        run: |
          git clone --depth 1 --recursive --branch ${{ env.TAG }} https://github.com/horsicq/DIE-engine.git .
      
      - name: Install build dependencies
        shell: bash
        run: |
          apt-get update
          
          apt-get install -y \
            build-essential \
            cmake \
            dpkg-dev \
            qt6-base-dev \
            qt6-base-dev-tools \
            qt6-tools-dev-tools \
            qt6-5compat-dev \
            libqt6svg6-dev \
            qt6-declarative-dev
      
      - name: Patch build_dpkg script
        run: |
          sed -i \
            '/^# Build DEBIAN\/control$/a\
          DEPS=$(dpkg-shlibdeps -O \
              "$WORK_DIR/usr/bin/die" \
              "$WORK_DIR/usr/bin/diec" \
              "$WORK_DIR/usr/bin/diel" 2>/dev/null | \
              sed -n '\''s/^shlibs:Depends=//p'\'')' \
            build_dpkg.sh
    
          sed -i \
            's/^Depends: libqt5core5a.*$/Depends: ${DEPS}/' \
            build_dpkg.sh
      
      - name: Build DIE DEB package
        run: |
          bash -x build_dpkg.sh
    
      - name: Upload DIE DEB
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: die-linux-arm64-artifact
          path: |
            release/*.deb